# Generated by Django 2.1.4 on 2019-02-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=256)),
                ('image_url', models.URLField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('rss_url', models.URLField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'News site',
                'verbose_name_plural': 'News sites',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.NewsSite'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.NewsSite'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'site')},
        ),
    ]
